version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
before_build:
    - nuget restore
build: 
    project: Intro.csproj
    restoreDirectory: NetCore_Develop
    publish_wap: true
