version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
before_build:
    - nuget restore
restoreDirectory:
    - NetCore_Develop
build: 
    project: Intro.csproj
    publish_wap: true
