version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
before_build:
    - nuget restore Intro\Intro.sln
build: 
    project: Intro\Intro.sln
    publish_wap: true
