// <auto-generated />
using MVC_Web_App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_Web_App.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20210327211958_Seed News data")]
    partial class SeedNewsdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_Web_App.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFake")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Jeremy Clarkson",
                            IsFake = true,
                            Text = "",
                            Title = "Humanity finally colonized the Mercury!!"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Svetlana Sokolova",
                            IsFake = true,
                            Text = "",
                            Title = "Increase your lifespan by 10 years, every morning you need..."
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "John Jones",
                            IsFake = false,
                            Text = "",
                            Title = "Scientists estimed the time of the vaccine invension: it is a summer of 2021"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Cerol Denvers",
                            IsFake = false,
                            Text = "",
                            Title = "Ukraine reduces the cost of its obligations!"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Jimmy Felon",
                            IsFake = true,
                            Text = "",
                            Title = "A species were discovered in Africa: it is blue legless cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
